import { test, expect } from '@playwright/test'

// Controlled edge sign-in and Gateway HTTP responses, actual browser/UI/API/DB.
// This does not exercise live institutional SSO or a real model provider.
test('mounted institutional entry preserves an existing deck, files and Gateway UI', async ({ page }) => {
  const browserIdentityHeaders: string[] = []
  const localLogouts: string[] = []
  page.on('request', request => {
    if (request.url().endsWith('/api/auth/logout')) localLogouts.push(request.url())
    for (const name of Object.keys(request.headers())) if (name.startsWith('x-cail-') || name === 'authorization') browserIdentityHeaders.push(name)
  })
  const anonymous = await page.request.get('/slide-maker/api/auth/me')
  expect(anonymous.status()).toBe(401)
  await page.goto('/fixture/sign-in')
  await page.getByRole('button', { name: 'Continue with institutional account' }).click()
  await expect(page.locator('.gallery-page')).toBeVisible({ timeout: 30000 })
  await expect(page.getByRole('button', { name: 'Password', exact: true })).toHaveCount(0)
  const thumbnail = await page.request.get('/slide-maker/thumbnail/existing-deck')
  expect(thumbnail.status()).toBe(200)
  expect(await thumbnail.text()).toContain('Persisted heading')
  await page.getByText('Existing institutional deck', { exact: true }).click()
  await expect(page).toHaveURL(/\/slide-maker\/deck\/existing-deck$/)
  await expect(page.locator('.slide-frame')).toContainText('Persisted heading')
  await expect(page.getByRole('combobox', { name: 'AI model' })).toHaveValue('fixture-model')
  await expect(page.getByText('Estimated quota remaining: 0%')).toBeVisible()
  const file = await page.request.get('/slide-maker/api/decks/existing-deck/files/abcdefghijklmnopqrstuvwx')
  expect(file.status()).toBe(200)
  expect(await file.text()).toBe('Existing CUID file contents')
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByRole('button', { name: 'Persisted heading', exact: true }).click()
  await page.locator('.slide-frame [contenteditable="true"]').fill('Edited persisted heading')
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await expect.poll(async () => JSON.stringify(await (await page.request.get('/slide-maker/api/decks/existing-deck')).json())).toContain('Edited persisted heading')
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Chat message' })
  await input.fill('Help with this existing slide')
  await page.getByTitle('Send (Enter)', { exact: true }).click()
  await expect(page.locator('.messages')).toContainText(/reference/i)
  await expect(page.locator('.messages')).not.toContainText('PRIVATE_PROVIDER_DETAIL')
  expect(await (await page.request.get('/fixture/state')).json()).toEqual({ attempts: 1, cancelled: false })
  await input.fill('Start a cancellable response')
  await page.getByTitle('Send (Enter)', { exact: true }).click()
  await expect(page.locator('.messages')).toContainText('Streaming fixture')
  await page.getByRole('button', { name: 'Stop streaming', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Stop streaming', exact: true })).toHaveCount(0)
  await expect.poll(async () => (await (await page.request.get('/fixture/state')).json()).cancelled).toBe(true)
  // A zero estimate remains informational; the request reaches Gateway once.
  const persisted = await (await page.request.get('/slide-maker/api/decks/existing-deck')).json()
  expect(persisted.name).toBe('Existing institutional deck')
  expect(await page.evaluate(() => JSON.stringify({ cookie: document.cookie, local: { ...localStorage }, session: { ...sessionStorage } }))).not.toMatch(/eyJ|fixture-session/)
  const identity = await (await page.request.get('/slide-maker/api/auth/me')).json()
  expect(identity.user.authentication).toBe('institutional')
  expect(JSON.stringify(identity)).not.toMatch(/eyJ|jwt|token/i)
  await page.getByTitle('Back to decks', { exact: true }).click()
  await page.getByRole('button', { name: 'Sign Out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Signed out of institutional fixture' })).toBeVisible()
  await expect(page).toHaveURL('/auth/logout')
  expect(localLogouts).toEqual([])
  expect(browserIdentityHeaders).toEqual([])
})
